import type { ServiceType } from '../domain/mealService';

export interface ParsedPassenger {
  seat: string;
  firstName: string;
  lastName: string;
  status?: string;
  codes: string[];
  rawText: string;
}

export interface FlightManifest {
  flightNumber: string;
  date: string;
  aircraftType: string;
  origin: string;
  destination: string;
  departureTime: string;
  serviceType: ServiceType;
  passengers: ParsedPassenger[];
  infantCount: number;
}

const pax = (
  seat: string,
  lastName: string,
  firstName: string,
  status?: string,
  codes: string[] = []
): ParsedPassenger => ({
  seat,
  firstName,
  lastName,
  status,
  codes: status ? [status, ...codes] : codes,
  rawText: `${seat} ${lastName}/${firstName}`,
});

// ─── Vuelo 1: AV210 BOG → JFK — 07:20 — Business Class Americas ──────────────
// 1 servicio: Desayuno (solo plato fuerte, sin entrada, sin despertar)
export const FLIGHT_AV210: FlightManifest = {
  flightNumber: 'AV210',
  date: '03 JUN 2026',
  aircraftType: 'B787-8',
  origin: 'BOG',
  destination: 'JFK',
  departureTime: '07:20',
  serviceType: 'AMERICAS',
  infantCount: 2,
  passengers: [
    // Business Class (filas 1-5, layout A/D/E/K)
    pax('1A', 'RAMIREZ', 'CARLOS', 'DIAM'),
    pax('1D', 'OSPINA', 'LUCIA', 'DIAM'),
    pax('1E', 'BOTERO', 'ANDRES', 'GOLD'),
    pax('1K', 'VILLA', 'CATALINA'),
    pax('2A', 'LONDONO', 'MARIO', 'GOLD', ['GFML']),
    pax('2D', 'RESTREPO', 'ANA'),
    pax('2E', 'CARDONA', 'PEDRO', 'DIAM'),
    pax('2K', 'ZAPATA', 'DIANA'),
    pax('3A', 'ARANGO', 'JUAN'),
    pax('3D', 'VELASQUEZ', 'SOFIA', 'GOLD'),
    pax('3E', 'RIOS', 'FELIPE'),
    pax('3K', 'GARCIA', 'VALENTINA'),
    pax('4A', 'MEJIA', 'SANTIAGO', 'DIAM'),
    pax('4E', 'CANO', 'MARIA'),
    pax('5D', 'HERRERA', 'ROBERTO', 'GOLD', ['VGML']),
    pax('5K', 'MONTOYA', 'ISABEL'),
    // Plus (filas 8-11)
    pax('8A', 'SALAZAR', 'JORGE'),
    pax('8B', 'FLOREZ', 'CAMILA'),
    pax('8C', 'MORALES', 'DIEGO'),
    pax('8D', 'AGUDELO', 'ISABELLA'),
    pax('8E', 'CASTAÑO', 'NICOLAS', undefined, ['BBML']),
    pax('8G', 'JIMENEZ', 'NATALIA'),
    pax('8J', 'OCHOA', 'MATEO'),
    pax('8K', 'TORO', 'VALERIA'),
    pax('9A', 'ESCOBAR', 'PABLO', undefined, ['WCHR']),
    pax('9B', 'URIBE', 'PAULA'),
    pax('9C', 'GIRALDO', 'ANDRES'),
    pax('9D', 'PEÑA', 'LINA'),
    pax('9E', 'AGUIRRE', 'GABRIEL'),
    pax('9F', 'BEDOYA', 'SARA'),
    pax('9G', 'CUERVO', 'TOMAS'),
    pax('9J', 'DIAZ', 'ELENA'),
    pax('9K', 'GUTIERREZ', 'RAFAEL'),
    pax('10A', 'HOYOS', 'JESSICA'),
    pax('10B', 'IBARRA', 'MARIO'),
    pax('10C', 'JARAMILLO', 'CATALINA'),
    pax('10D', 'LEIVA', 'HECTOR'),
    pax('10J', 'LOPERA', 'ALEJANDRO'),
    pax('10K', 'MARIN', 'ANDREA'),
    // Economy (filas 12-41)
    pax('12A', 'NARANJO', 'DANIELA'),
    pax('12B', 'OBANDO', 'CARLOS', undefined, ['PETC']),
    pax('12C', 'PARDO', 'NATALIA'),
    pax('12D', 'QUINTERO', 'OSCAR'),
    pax('12E', 'RENDON', 'LORENA'),
    pax('12F', 'SIERRA', 'PABLO'),
    pax('12G', 'TAMAYO', 'ANDREA'),
    pax('12J', 'UPEGUI', 'JORGE'),
    pax('12K', 'VASQUEZ', 'MARIA'),
    pax('14A', 'WALTEROS', 'ESTEBAN'),
    pax('14B', 'YEPES', 'CLAUDIA', undefined, ['VGML']),
    pax('14C', 'ZULUAGA', 'FELIX'),
    pax('14D', 'ACOSTA', 'ROSA'),
    pax('14E', 'BERNAL', 'ANDRES'),
    pax('14F', 'CALDERON', 'BEATRIZ'),
    pax('14G', 'DAVILA', 'IVAN'),
    pax('14J', 'ERASO', 'PILAR'),
    pax('14K', 'FAJARDO', 'ERNESTO'),
    pax('15A', 'GOMEZ', 'SILVIA'),
    pax('15B', 'HINCAPIE', 'MARCO'),
    pax('15E', 'ISAZA', 'GABRIELA', undefined, ['GFML']),
    pax('15F', 'JAIMES', 'RAUL'),
    pax('15G', 'KURE', 'HELENA'),
    pax('16A', 'LEAL', 'JUAN', undefined, ['WCHS']),
    pax('16B', 'MACIAS', 'TERESA'),
    pax('16C', 'NIETO', 'CESAR'),
    pax('16D', 'OLARTE', 'ALICIA'),
    pax('16E', 'PALACIOS', 'MANUEL'),
    pax('16F', 'QUIJANO', 'PATRICIA'),
    pax('16G', 'ROJAS', 'RODRIGO'),
    pax('16K', 'SERNA', 'ADRIANA'),
    pax('17A', 'TOVAR', 'ABEL'),
    pax('17B', 'URREA', 'NORA'),
    pax('17C', 'VASCO', 'HUGO'),
    pax('17D', 'WILLS', 'ANGELA'),
    pax('17E', 'YATES', 'VICTOR'),
    pax('17F', 'ZAPATA', 'IRENE'),
    pax('17G', 'ANGEL', 'CRISTIAN'),
    pax('17J', 'BAENA', 'YOLANDA'),
    pax('17K', 'CAMPO', 'JAIME'),
    pax('18A', 'DAZA', 'CLAUDIA'),
    pax('18C', 'ELIAS', 'FRANCISCO'),
    pax('18D', 'FRANCO', 'ROSARIO'),
    pax('18J', 'GALVIS', 'GILBERTO'),
    pax('19A', 'HENAO', 'LIDIA'),
    pax('19B', 'IDARRAGA', 'ERNESTO', undefined, ['CHML']),
    pax('19C', 'INSIGNARES', 'AMANDA'),
    pax('19D', 'JARABA', 'XAVIER'),
    pax('19E', 'KLEE', 'ROCIO'),
    pax('19F', 'LADINO', 'IVAN'),
    pax('19G', 'LOZANO', 'SUSANA'),
    pax('20A', 'MANOTAS', 'ABELARDO'),
    pax('20B', 'NARANJO', 'NANCY'),
    pax('20C', 'OSSA', 'DARIO'),
    pax('20D', 'PIZANO', 'PAOLA'),
    pax('20E', 'QUIROZ', 'NELSON'),
    pax('20F', 'RANGEL', 'LIZBETH'),
    pax('21A', 'RENGIFO', 'DIANA', undefined, ['SVAN']),
    pax('21B', 'SAMUDIO', 'EDGAR'),
    pax('21C', 'TERNERA', 'LUISA'),
    pax('21D', 'URQUIJO', 'ALFREDO'),
    pax('22A', 'VALENCIA', 'BERNARDO'),
    pax('22B', 'VIDALES', 'CECILIA'),
    pax('22C', 'WILLS', 'STEFAN'),
    pax('22D', 'YABRUDY', 'BEATRIZ'),
    pax('23A', 'ZUÑIGA', 'JOSE'),
    pax('23B', 'ARBELAEZ', 'AMPARO'),
    pax('24A', 'BAUTISTA', 'ELSA'),
    pax('24B', 'CIFUENTES', 'FABIAN'),
    pax('25A', 'CORTES', 'INES', undefined, ['MEML']),
    pax('25B', 'DUQUE', 'JOAQUIN'),
    pax('25C', 'ESTEVEZ', 'KATIA'),
    pax('26A', 'FABARA', 'REBECA'),
    pax('26B', 'GARZON', 'SIEGFRIED'),
    pax('27A', 'HUERTAS', 'VIVIANA'),
    pax('27B', 'IBAGON', 'WILSON'),
    pax('28A', 'JANSSEN', 'ALBA'),
    pax('28B', 'KINGMAN', 'BORIS'),
    pax('29A', 'LADINO', 'CLARA', undefined, ['FSML']),
    pax('29B', 'MARULANDA', 'DARIO'),
    pax('30A', 'NINO', 'ELSA'),
    pax('30B', 'OBANDO', 'FABIAN'),
    pax('31A', 'PENAGOS', 'GISELA'),
    pax('31B', 'QUIROS', 'HAROLD'),
    pax('32A', 'RINCON', 'IMELDA'),
    pax('32B', 'SAAVEDRA', 'JULIO'),
    pax('33A', 'TIRADO', 'KAROL'),
    pax('33B', 'URIBE', 'LEOVIGILDO'),
    pax('34A', 'VENEGAS', 'MAGNOLIA'),
    pax('34B', 'WALTEROS', 'NICOLAS'),
    pax('35A', 'YEPEZ', 'OMAR'),
    pax('36A', 'ZAPATA', 'PIEDAD'),
    pax('36B', 'ACEVEDO', 'QUIRINO'),
    pax('37A', 'BORDA', 'REBECA'),
    pax('37B', 'CARREÑO', 'SIEGFRIED'),
    pax('38A', 'DAVILA', 'TERESA'),
    pax('39A', 'ERASO', 'ULPIANO'),
    pax('40A', 'FIERRO', 'VENUS'),
    pax('41A', 'GALINDO', 'WALTER'),
  ],
};

// ─── Vuelo 2: AV026 BOG → MAD — 13:48 — Insignia ────────────────────────────
// 2 servicios: Almuerzo + Desayuno (entrada+plato+despertar)
export const FLIGHT_AV026: FlightManifest = {
  flightNumber: 'AV026',
  date: '03 JUN 2026',
  aircraftType: 'B787-8',
  origin: 'BOG',
  destination: 'MAD',
  departureTime: '13:48',
  serviceType: 'INSIGNIA',
  infantCount: 1,
  passengers: [
    // Business Class
    pax('1A', 'ECHEVERRI', 'RAFAEL', 'DIAM'),
    pax('1D', 'PALACIO', 'HELENA', 'DIAM'),
    pax('1E', 'ARBOLEDA', 'SERGIO', 'GOLD'),
    pax('1K', 'VELEZ', 'CRISTINA'),
    pax('2A', 'OSORIO', 'BEATRIZ', 'GOLD', ['VGML']),
    pax('2D', 'SALCEDO', 'HECTOR'),
    pax('2E', 'TORO', 'ADRIANA'),
    pax('2K', 'URIBE', 'CAMILO'),
    pax('3A', 'VILLA', 'DIANA', 'DIAM'),
    pax('3D', 'ZULUAGA', 'ERNESTO'),
    pax('3E', 'AGUDELO', 'FERNANDA', 'GOLD'),
    pax('3K', 'BETANCUR', 'GONZALO'),
    pax('4A', 'CADAVID', 'HELENA'),
    pax('4E', 'DAVALOS', 'IGNACIO', 'GOLD', ['GFML']),
    pax('5D', 'ESCOBAR', 'JANETH'),
    pax('5K', 'FRANCO', 'KENIA'),
    // Plus (filas 8-11)
    pax('8A', 'GIRALDO', 'LISARDO'),
    pax('8B', 'HOYOS', 'MARTHA'),
    pax('8C', 'ISAZA', 'NELSON'),
    pax('8D', 'JARAMILLO', 'ORFILIA'),
    pax('8E', 'LONDONO', 'PATRICIO', undefined, ['BBML']),
    pax('8G', 'MONTOYA', 'SARA'),
    pax('8J', 'NOREÑA', 'TOMAS'),
    pax('8K', 'OCAMPO', 'ISABEL'),
    pax('9A', 'PALACIO', 'SAMUEL', undefined, ['WCHR']),
    pax('9B', 'QUIJADA', 'TERESA'),
    pax('9C', 'RESTREPO', 'UVALDO'),
    pax('9D', 'SEPULVEDA', 'VIOLETA'),
    pax('9E', 'TABARES', 'WILLIAM'),
    pax('9F', 'URREA', 'XIMENA'),
    pax('9G', 'VASCO', 'YESID'),
    pax('9J', 'ARBELAEZ', 'ZOILA'),
    pax('9K', 'BEDOYA', 'ALBA'),
    pax('10A', 'CARVAJAL', 'BLAS'),
    pax('10B', 'DUQUE', 'CLARA'),
    pax('10C', 'ESTRADA', 'DARIO'),
    pax('10J', 'FLOREZ', 'ELENA'),
    pax('10K', 'GAVIRIA', 'FABRICIO'),
    // Economy
    pax('12A', 'HENAO', 'GRISELDA'),
    pax('12B', 'IDARRAGA', 'HUMBERTO'),
    pax('12C', 'JIMENEZ', 'ISABEL'),
    pax('12D', 'KURI', 'JORGE'),
    pax('12E', 'LOPERA', 'KAREN'),
    pax('12K', 'MOLINA', 'LUIS'),
    pax('14A', 'NARANJO', 'MARIA'),
    pax('14B', 'OBANDO', 'NESTOR'),
    pax('14C', 'PIEDRAHITA', 'OLGA'),
    pax('14D', 'QUINTERO', 'PABLO'),
    pax('14E', 'RINCON', 'RAQUEL', undefined, ['PETC']),
    pax('14K', 'SALAZAR', 'SERGIO'),
    pax('15A', 'TRUJILLO', 'TATIANA'),
    pax('15B', 'VASQUEZ', 'URIEL'),
    pax('15C', 'WILLS', 'VIVIANA'),
    pax('15D', 'YEPES', 'XAVIER'),
    pax('16A', 'ZAPATA', 'YENNY'),
    pax('16B', 'ACOSTA', 'ZEUS'),
    pax('16C', 'BERNAL', 'ALBA'),
    pax('16D', 'CASTILLO', 'BORIS'),
    pax('17A', 'DELGADO', 'CARMEN'),
    pax('17B', 'ECHAVARRIA', 'DELFIN'),
    pax('17D', 'FIGUEROA', 'ESMERALDA'),
    pax('18A', 'GARCIA', 'FELIX'),
    pax('18B', 'HINCAPIE', 'GLORIA', undefined, ['CHML']),
    pax('18C', 'IBARRA', 'HECTOR'),
    pax('18D', 'JAIMES', 'INES'),
    pax('19A', 'LEMOS', 'JAVIER'),
    pax('19B', 'MAZO', 'KARINA'),
    pax('19C', 'NIETO', 'LETICIA'),
    pax('19D', 'OSSA', 'MARCOS'),
    pax('20A', 'PARRA', 'NANCY'),
    pax('20B', 'QUICENO', 'OSCAR'),
    pax('20C', 'RODRIGUEZ', 'PAOLA'),
    pax('20D', 'SANCHEZ', 'RAUL'),
    pax('21A', 'TEJADA', 'SONIA'),
    pax('21B', 'UPEGUI', 'TOMAS'),
    pax('21C', 'VELASQUEZ', 'UNA'),
    pax('22A', 'ZULUAGA', 'VICTOR'),
    pax('22B', 'ARENAS', 'WENDY'),
    pax('22C', 'BAENA', 'XAVIER'),
    pax('23A', 'CALLE', 'YOLANDA'),
    pax('23B', 'DIAZ', 'ZULMA'),
    pax('24A', 'ERASO', 'ANDRES'),
    pax('24B', 'FRANCO', 'BLANCA'),
    pax('25A', 'GARCIA', 'CAMILO', undefined, ['FSML']),
    pax('25B', 'HERRERA', 'DIANA'),
    pax('26A', 'IRISARRI', 'EDUARDO'),
    pax('26B', 'JORDAN', 'FANNY'),
    pax('27A', 'KUREISHI', 'GABRIEL'),
    pax('27B', 'LEIVA', 'HASSAN'),
    pax('28A', 'MORALES', 'INGRID'),
    pax('28B', 'NIEVES', 'JAIR'),
    pax('29A', 'OLARTE', 'KELLY'),
    pax('29B', 'PALOMINO', 'LIDA'),
    pax('30A', 'RIOS', 'MIGUEL'),
    pax('30B', 'SERNA', 'NUBIA'),
    pax('31A', 'TAMAYO', 'OMAR'),
    pax('32A', 'URIBE', 'PILAR'),
    pax('32B', 'VEGA', 'QUIRINO'),
    pax('33A', 'WALTEROS', 'ROCIO'),
    pax('33B', 'YATES', 'SAUL'),
    pax('34A', 'ZAPATA', 'TERESA'),
    pax('36A', 'ANGEL', 'ULISES'),
    pax('37A', 'BOTERO', 'VALENTINA'),
    pax('38A', 'CORTES', 'WALTER'),
    pax('39A', 'DAVILA', 'XIMENA'),
    pax('40A', 'ERAZO', 'YAMILE'),
    pax('41A', 'FAJARDO', 'ZEUS'),
  ],
};

// ─── Vuelo 3: AV120 BOG → LHR — 23:25 — Insignia ────────────────────────────
// 2 servicios: Cena + Desayuno (entrada+plato+despertar)
export const FLIGHT_AV120: FlightManifest = {
  flightNumber: 'AV120',
  date: '03 JUN 2026',
  aircraftType: 'B787-8',
  origin: 'BOG',
  destination: 'LHR',
  departureTime: '23:25',
  serviceType: 'INSIGNIA',
  infantCount: 2,
  passengers: [
    // Business Class
    pax('1A', 'LLINÁS', 'GUSTAVO', 'DIAM'),
    pax('1D', 'BARRIOS', 'MARINA', 'DIAM'),
    pax('1E', 'CAMPO', 'DAVID', 'GOLD'),
    pax('1K', 'DIAZ', 'CONSUELO'),
    pax('2A', 'ESPINOSA', 'FIDEL', 'DIAM'),
    pax('2D', 'FUENTES', 'GRACIELA'),
    pax('2E', 'GAMBOA', 'HERNAN'),
    pax('2K', 'IBAÑEZ', 'JACINTA', undefined, ['VGML']),
    pax('3A', 'JARABA', 'KEVIN', 'GOLD'),
    pax('3D', 'LEAL', 'LINA'),
    pax('3E', 'MARTINEZ', 'MARIO'),
    pax('3K', 'NAVARRO', 'NATALIA', 'GOLD'),
    pax('4A', 'OLMOS', 'OMAR'),
    pax('4E', 'POLO', 'PATRICIA', undefined, ['GFML']),
    pax('5D', 'QUIÑONES', 'RAUL', 'DIAM'),
    pax('5K', 'REALES', 'SANDRA'),
    // Plus (filas 8-11)
    pax('8A', 'SIERRA', 'TOMAS'),
    pax('8B', 'TORRES', 'URSULA'),
    pax('8C', 'ULLOA', 'VALENTINA'),
    pax('8D', 'VIVEROS', 'WILLIAM'),
    pax('8E', 'YAÑEZ', 'XAVIER', undefined, ['BBML']),
    pax('8G', 'ZARATE', 'YOLANDA'),
    pax('8J', 'AVILEZ', 'ZEUS'),
    pax('8K', 'BAYONA', 'ALBA'),
    pax('9A', 'CABAS', 'BORIS', undefined, ['WCHR']),
    pax('9B', 'DACONTE', 'CARMEN'),
    pax('9C', 'ECHEVERRIA', 'DIEGO'),
    pax('9D', 'FALS', 'ELENA'),
    pax('9E', 'GARCIA', 'FRANK'),
    pax('9F', 'HERREÑO', 'GINA'),
    pax('9G', 'INSIGNARES', 'HORACIO'),
    pax('9J', 'JARAMILLO', 'IRIS'),
    pax('9K', 'KURE', 'JOSE'),
    pax('10A', 'LARA', 'KATIA'),
    pax('10B', 'MANCILLA', 'LEANDRO'),
    pax('10C', 'NIÑO', 'MAGNOLIA'),
    pax('10J', 'OROZCO', 'NICOLAS'),
    pax('10K', 'PALMA', 'OFELIA'),
    // Economy
    pax('12A', 'QUEVEDO', 'PEDRO'),
    pax('12B', 'RAMOS', 'QUINTIN'),
    pax('12C', 'SUAREZ', 'RAQUEL'),
    pax('12D', 'TOVAR', 'SERGIO', undefined, ['PETC']),
    pax('12E', 'URIBE', 'TATIANA'),
    pax('12K', 'VASQUEZ', 'URIEL'),
    pax('14A', 'WALTEROS', 'VALERIA'),
    pax('14B', 'YEPEZ', 'WILLIAM'),
    pax('14C', 'ZAPATA', 'XIOMARA'),
    pax('14D', 'ARAGON', 'YURI'),
    pax('14E', 'BALLESTAS', 'ZEUS'),
    pax('14K', 'CANTILLO', 'ALBA'),
    pax('15A', 'DORIA', 'BLAS'),
    pax('15B', 'ELLES', 'CLARA'),
    pax('15C', 'FONTALVO', 'DARIO'),
    pax('15D', 'GUERRERO', 'ELENA'),
    pax('16A', 'HERRERA', 'FELIX'),
    pax('16B', 'INSIGNARES', 'GLORIA'),
    pax('16C', 'JABBA', 'HORACIO', undefined, ['MEML']),
    pax('16D', 'KURE', 'IRIS'),
    pax('17A', 'LEMAITRE', 'JOSE'),
    pax('17B', 'MELO', 'KAREN'),
    pax('17D', 'NAVARRO', 'LUIS'),
    pax('18A', 'ORTEGA', 'MARIA'),
    pax('18B', 'PATERNINA', 'NESTOR', undefined, ['CHML']),
    pax('18C', 'QUINTERO', 'OLGA'),
    pax('18D', 'RAMIREZ', 'PABLO'),
    pax('19A', 'SALCEDO', 'QUIJANO'),
    pax('19B', 'TOBAR', 'ROSARIA'),
    pax('19D', 'URQUIJO', 'SAMUEL'),
    pax('20A', 'VILLADIEGO', 'TERESA'),
    pax('20B', 'WILLS', 'ULISES'),
    pax('21A', 'YEPES', 'VALENTINA'),
    pax('21B', 'ZUÑIGA', 'WALTER'),
    pax('22A', 'ACOSTA', 'XIMENA'),
    pax('22B', 'BUELVAS', 'YOLANDA'),
    pax('23A', 'CAMPO', 'ZEUS'),
    pax('23B', 'DAZA', 'ALBA'),
    pax('24A', 'ELIAS', 'BEATRIZ'),
    pax('24B', 'FLOREZ', 'CAMILO'),
    pax('25A', 'GARCIA', 'DIANA'),
    pax('25B', 'HERRAN', 'EDGAR'),
    pax('26A', 'IBARRA', 'FANNY'),
    pax('26B', 'JARABA', 'GABRIEL'),
    pax('27A', 'KURE', 'HELEN'),
    pax('27B', 'LEAL', 'IGNACIO'),
    pax('28A', 'MANOTAS', 'JULIA'),
    pax('28B', 'NIETO', 'KEVIN'),
    pax('29A', 'OTALVARO', 'LUPE'),
    pax('29B', 'PACHECO', 'MARIO'),
    pax('30A', 'QUINTANA', 'NURIA'),
    pax('31A', 'ROMERO', 'OMAR'),
    pax('32A', 'SIERRA', 'PETRA'),
    pax('33A', 'TOVAR', 'QUINTIN'),
    pax('34A', 'URIBE', 'REBECA'),
    pax('36A', 'VASQUEZ', 'SAUL'),
    pax('37A', 'WILLS', 'TERESA'),
    pax('38A', 'YEPES', 'ULISES'),
    pax('39A', 'ZUÑIGA', 'VENUS'),
    pax('40A', 'ANGEL', 'WALTER'),
    pax('41A', 'BOTERO', 'XIMENA'),
  ],
};

export const DEMO_FLIGHTS = [FLIGHT_AV210, FLIGHT_AV026, FLIGHT_AV120];
