export interface ParsedPassenger {
  seat: string;
  firstName: string;
  lastName: string;
  status?: string;
  codes: string[];
  rawText: string;
}

export interface FlightManifest {
  flightNumber: string;
  date: string;
  aircraftType: string;
  origin: string;
  destination: string;
  passengers: ParsedPassenger[];
  infantCount: number;
}

const pax = (
  seat: string,
  lastName: string,
  firstName: string,
  status?: string,
  codes: string[] = []
): ParsedPassenger => ({
  seat,
  firstName,
  lastName,
  status,
  codes: status ? [status, ...codes] : codes,
  rawText: `${seat} ${lastName}/${firstName}`,
});

// ─── Vuelo 1: AV028 BOG → JFK — B787-8 (internacional) ───────────────────────
export const FLIGHT_AV028: FlightManifest = {
  flightNumber: 'AV028',
  date: '03 JUN 2026',
  aircraftType: 'B787-8',
  origin: 'BOG',
  destination: 'JFK',
  infantCount: 3,
  passengers: [
    // Business Class (filas 1-5, layout A/D/E/K)
    pax('1A', 'RODRIGUEZ', 'ANDRES', 'DIAM'),
    pax('1D', 'MARTINEZ', 'CLAUDIA', 'DIAM'),
    pax('1E', 'PEREZ', 'JUAN', 'GOLD'),
    pax('1K', 'GARCIA', 'SOFIA'),
    pax('2A', 'LOPEZ', 'CARLOS', 'GOLD', ['GFML']),
    pax('2D', 'HERNANDEZ', 'ANA'),
    pax('2E', 'TORRES', 'MIGUEL', 'DIAM'),
    pax('2K', 'VARGAS', 'LUCIA'),
    pax('3A', 'CASTILLO', 'PABLO'),
    pax('3D', 'MORALES', 'VALENTINA', 'GOLD'),
    pax('3E', 'JIMENEZ', 'ROBERTO'),
    pax('3K', 'ROMERO', 'DIANA'),
    pax('4A', 'GUERRERO', 'SERGIO', 'DIAM'),
    pax('4E', 'MEDINA', 'CAROLINA'),
    pax('5D', 'ORTEGA', 'FELIPE', 'GOLD', ['VGML']),
    pax('5K', 'REYES', 'NATALIA'),
    // Plus Class (filas 8-11)
    pax('8A', 'SILVA', 'JORGE'),
    pax('8B', 'MENDOZA', 'CAMILA'),
    pax('8C', 'SANTOS', 'DIEGO'),
    pax('8D', 'RAMIREZ', 'ISABELLA'),
    pax('8E', 'FLORES', 'SEBASTIAN', undefined, ['BBML']),
    pax('8G', 'DIAZ', 'MARIANA'),
    pax('8J', 'VEGA', 'NICOLAS'),
    pax('8K', 'RUIZ', 'VALERIA'),
    pax('9A', 'MORENO', 'SANTIAGO', undefined, ['WCHR']),
    pax('9B', 'GUTIERREZ', 'PAULA'),
    pax('9C', 'RAMOS', 'ANDRES'),
    pax('9D', 'ACOSTA', 'LINA'),
    pax('9E', 'PEÑA', 'GABRIEL'),
    pax('9F', 'HERRERA', 'SARA'),
    pax('9G', 'AGUILAR', 'TOMAS'),
    pax('9J', 'CARDENAS', 'ELENA'),
    pax('9K', 'MEZA', 'RAFAEL'),
    pax('10A', 'GUERRERO', 'JESSICA'),
    pax('10B', 'PAREDES', 'MARIO'),
    pax('10C', 'DELGADO', 'CATALINA'),
    pax('10D', 'FUENTES', 'HECTOR'),
    pax('10J', 'CABRERA', 'ALEJANDRO'),
    pax('10K', 'SALINAS', 'ANDREA'),
    // Economy (filas 12-41)
    pax('12A', 'CAMPOS', 'DANIELA'),
    pax('12B', 'ESPINOZA', 'CARLOS', undefined, ['PETC']),
    pax('12C', 'PALACIOS', 'NATALIA'),
    pax('12D', 'MIRANDA', 'OSCAR'),
    pax('12E', 'CORDOVA', 'LORENA'),
    pax('12F', 'NAVARRO', 'PABLO'),
    pax('12G', 'OJEDA', 'ANDREA'),
    pax('12J', 'CONTRERAS', 'JORGE'),
    pax('12K', 'IBARRA', 'MARIA'),
    pax('14A', 'SERRANO', 'ESTEBAN'),
    pax('14B', 'MARQUEZ', 'CLAUDIA', undefined, ['VGML']),
    pax('14C', 'PONCE', 'FELIX'),
    pax('14D', 'ZAMORA', 'ROSA'),
    pax('14E', 'CARRASCO', 'ANDRES'),
    pax('14F', 'MONTOYA', 'BEATRIZ'),
    pax('14G', 'SOTO', 'IVAN'),
    pax('14J', 'TRUJILLO', 'PILAR'),
    pax('14K', 'LUNA', 'ERNESTO'),
    pax('15A', 'BRAVO', 'SILVIA'),
    pax('15B', 'AVILA', 'MARCO'),
    pax('15E', 'PERALTA', 'GABRIELA', undefined, ['GFML']),
    pax('15F', 'ESCOBAR', 'RAUL'),
    pax('15G', 'CUEVAS', 'HELENA'),
    pax('16A', 'ARENAS', 'JUAN', undefined, ['WCHS']),
    pax('16B', 'GUZMAN', 'TERESA'),
    pax('16C', 'MOLINA', 'CESAR'),
    pax('16D', 'BERMUDEZ', 'ALICIA'),
    pax('16E', 'TAPIA', 'MANUEL'),
    pax('16F', 'VELAZQUEZ', 'PATRICIA'),
    pax('16G', 'CISNEROS', 'RODRIGO'),
    pax('16K', 'OROZCO', 'ADRIANA'),
    pax('17A', 'FIGUEROA', 'ABEL'),
    pax('17B', 'GALVEZ', 'NORA'),
    pax('17C', 'MARIN', 'HUGO'),
    pax('17D', 'NUNEZ', 'ANGELA'),
    pax('17E', 'PALMA', 'VICTOR'),
    pax('17F', 'RIOS', 'IRENE'),
    pax('17G', 'SUAREZ', 'CRISTIAN'),
    pax('17J', 'VERA', 'YOLANDA'),
    pax('17K', 'ALARCON', 'JAIME'),
    pax('18A', 'BARROS', 'CLAUDIA'),
    pax('18C', 'CEDILLO', 'FRANCISCO'),
    pax('18D', 'DOMINGUEZ', 'ROSARIO'),
    pax('18J', 'ENCISO', 'GILBERTO'),
    pax('19A', 'FAJARDO', 'LIDIA'),
    pax('19B', 'GARAY', 'ERNESTO', undefined, ['CHML']),
    pax('19C', 'IBAGON', 'AMANDA'),
    pax('19D', 'JARAMILLO', 'XAVIER'),
    pax('19E', 'LOZANO', 'ROCIO'),
    pax('19F', 'MACIAS', 'IVAN'),
    pax('19G', 'NARANJO', 'SUSANA'),
    pax('19J', 'OLEA', 'DANIEL'),
    pax('19K', 'PEDRAZA', 'MIREYA'),
    pax('20A', 'QUINTERO', 'ABELARDO'),
    pax('20B', 'RANGEL', 'NANCY'),
    pax('20C', 'SAAVEDRA', 'DARIO'),
    pax('20D', 'TIRADO', 'PAOLA'),
    pax('20E', 'URIBE', 'NELSON'),
    pax('20F', 'VENEGAS', 'LIZBETH'),
    pax('20J', 'WALTEROS', 'DIANA'),
    pax('20K', 'YEPEZ', 'MATEO'),
    pax('21A', 'ZAPATA', 'CLAUDIA', undefined, ['SVAN']),
    pax('21B', 'ARBELAEZ', 'EDGAR'),
    pax('21C', 'BERNAL', 'LUISA'),
    pax('21D', 'CANO', 'ALFREDO'),
    pax('21E', 'DIOSES', 'FLOR'),
    pax('21F', 'ESTRADA', 'MARCO'),
    pax('21G', 'FRANCO', 'PILAR'),
    pax('21J', 'GAONA', 'RODRIGO'),
    pax('21K', 'HOYOS', 'CARMENZA'),
    pax('22A', 'ISAZA', 'BERNARDO'),
    pax('22B', 'JAIMES', 'CECILIA'),
    pax('22C', 'KLEE', 'STEFAN'),
    pax('22D', 'LONDONO', 'BEATRIZ'),
    pax('22E', 'MURILLO', 'ARNALDO'),
    pax('22F', 'NIETO', 'JENNIFER'),
    pax('22G', 'OSPINA', 'GILBERTO'),
    pax('22J', 'PIZANO', 'HELENA'),
    pax('23A', 'QUIROZ', 'JOSE'),
    pax('23B', 'RENGIFO', 'AMPARO'),
    pax('23C', 'SAMUDIO', 'BLAS'),
    pax('23D', 'TERNERA', 'PATRICIA'),
    pax('23E', 'URQUIJO', 'CESAR'),
    pax('24A', 'VAQUERO', 'ELENA'),
    pax('24B', 'WILCHES', 'ENRIQUE'),
    pax('24C', 'YEPES', 'GLORIA'),
    pax('24D', 'ZULUAGA', 'HORACIO'),
    pax('25A', 'ABELLO', 'INES', undefined, ['MEML']),
    pax('25B', 'BLANCO', 'JOAQUIN'),
    pax('25C', 'CALDERON', 'KATIA'),
    pax('25D', 'DAZA', 'LEANDRO'),
    pax('25E', 'ECHEVERRI', 'MIRIAM'),
    pax('25F', 'FIERRO', 'NESTOR'),
    pax('25G', 'GALINDO', 'OFELIA'),
    pax('25J', 'HINCAPIE', 'PATRICIO'),
    pax('25K', 'INSIGNARES', 'QUINTIN'),
    pax('26A', 'JARABA', 'REBECA'),
    pax('26B', 'KOPPEL', 'SIEGFRIED'),
    pax('26C', 'LLANOS', 'TANIA'),
    pax('26D', 'MACIAS', 'UGO'),
    pax('27A', 'NEIRA', 'VIVIANA'),
    pax('27B', 'OVIEDO', 'WILSON'),
    pax('27C', 'PACHON', 'XIOMARA'),
    pax('27D', 'QUIJANO', 'YURI'),
    pax('27E', 'RESTREPO', 'ZOILO'),
    pax('28A', 'SARMIENTO', 'ALBA'),
    pax('28B', 'TOVAR', 'BORIS'),
    pax('28C', 'USAQUÉN', 'CLARA', undefined, ['FSML']),
    pax('28D', 'VIDALES', 'DARIO'),
    pax('29A', 'AVELLA', 'ELSA'),
    pax('29B', 'BAUTISTA', 'FABIAN'),
    pax('29C', 'CIFUENTES', 'GISELA'),
    pax('29D', 'DUQUE', 'HAROLD'),
    pax('29E', 'ESTEVEZ', 'IMELDA'),
    pax('30A', 'FABARA', 'JULIO', undefined, ['DEPA']),
    pax('30B', 'GARZON', 'KAROL'),
    pax('30C', 'HUERTAS', 'LEOVIGILDO'),
    pax('30D', 'IBATA', 'MAGNOLIA'),
    pax('30F', 'JANSSEN', 'NICOLAS'),
    pax('31A', 'KINGMAN', 'OMAR'),
    pax('31B', 'LADINO', 'PIEDAD'),
    pax('31C', 'MARULANDA', 'QUIRINO'),
    pax('31D', 'NINO', 'ROSALBA'),
    pax('31E', 'OBANDO', 'SEGUNDO'),
    pax('31F', 'PENAGOS', 'TERESA'),
    pax('31G', 'QUIROS', 'ULPIANO'),
    pax('31J', 'RINCON', 'VENUS'),
    pax('32A', 'SIERRA', 'WALTER'),
    pax('32B', 'TAMAYO', 'XIMENA'),
    pax('32C', 'UMAÑA', 'YOLANDA'),
    pax('32D', 'VASQUEZ', 'ZOILA'),
    pax('32E', 'AREVALO', 'ALBA'),
    pax('33A', 'BORDA', 'CAMILO'),
    pax('33B', 'CORREA', 'DIANA'),
    pax('33C', 'DEVIA', 'EDGAR'),
    pax('33D', 'ELIAS', 'FLORENCIA'),
    pax('33G', 'FONTALVO', 'GABRIEL'),
    pax('34A', 'GIRALDO', 'HELEN'),
    pax('34B', 'HERNANDEZ', 'IGNACIO'),
    pax('34C', 'IBANEZ', 'JULIA'),
    pax('34D', 'JIMENEZ', 'KEVIN'),
    pax('34J', 'KURE', 'LUPE'),
    pax('34K', 'LEAL', 'MAXIMILIANO'),
    pax('36A', 'MESA', 'NURIA'),
    pax('36B', 'NANEZ', 'OLGA'),
    pax('36C', 'OROZCO', 'PEDRO'),
    pax('36D', 'PARDO', 'QUITERIA'),
    pax('36E', 'QUINTANA', 'RIGOBERTO'),
    pax('36F', 'RINCON', 'SOLEDAD'),
    pax('36G', 'SABOGAL', 'TEODORO'),
    pax('36K', 'TEJADA', 'URSULA'),
    pax('37A', 'ULLOA', 'VIRGINIA'),
    pax('37B', 'VALENCIA', 'WALTER'),
    pax('37C', 'WILLS', 'XIMENA'),
    pax('38A', 'YABRUDY', 'YENNY'),
    pax('38B', 'ZAMORA', 'ZEUS'),
    pax('39A', 'ACEVEDO', 'ANGELES'),
    pax('39B', 'BALLESTEROS', 'BLADIMIR'),
    pax('39C', 'CARREÑO', 'CELESTINO'),
    pax('40A', 'DAVILA', 'DOLORES'),
    pax('40B', 'ERASO', 'EUGENIO'),
    pax('40C', 'FIERRO', 'FLORA'),
    pax('40D', 'GAONA', 'GUSTAVO'),
    pax('41A', 'HERNANDEZ', 'HIPOLITA'),
    pax('41B', 'IRIARTE', 'ISIDRO'),
  ],
};

// ─── Vuelo 2: AV9114 BOG → MDE — A320 (doméstico) ────────────────────────────
export const FLIGHT_AV9114: FlightManifest = {
  flightNumber: 'AV9114',
  date: '03 JUN 2026',
  aircraftType: 'A320',
  origin: 'BOG',
  destination: 'MDE',
  infantCount: 1,
  passengers: [
    // Business (filas 1-3, layout A/C/D/K)
    pax('1A', 'ECHEVERRI', 'CARLOS', 'DIAM'),
    pax('1C', 'PATIÑO', 'GLORIA', 'GOLD'),
    pax('1D', 'ARBOLEDA', 'MARIO', 'DIAM'),
    pax('1K', 'VELEZ', 'LILIANA'),
    pax('2A', 'OSORIO', 'BEATRIZ', 'GOLD', ['GFML']),
    pax('2C', 'SALCEDO', 'HECTOR'),
    pax('2D', 'TORO', 'ADRIANA'),
    pax('2K', 'URIBE', 'CAMILO'),
    pax('3A', 'VILLA', 'DIANA'),
    pax('3C', 'ZULUAGA', 'ERNESTO'),
    pax('3D', 'AGUDELO', 'FERNANDA'),
    // Plus (filas 4-11, layout A/B/C/D/E/K)
    pax('4A', 'BETANCUR', 'GONZALO', undefined, ['WCHR']),
    pax('4B', 'CADAVID', 'HELENA'),
    pax('4C', 'DAVALOS', 'IGNACIO'),
    pax('4D', 'ESCOBAR', 'JANETH'),
    pax('4E', 'FRANCO', 'KENIA'),
    pax('4K', 'GIRALDO', 'LISARDO'),
    pax('5A', 'HOYOS', 'MARTHA'),
    pax('5B', 'ISAZA', 'NELSON'),
    pax('5C', 'JARAMILLO', 'ORFILIA'),
    pax('5D', 'LONDONO', 'PATRICIO'),
    pax('5E', 'MONTOYA', 'QUIJANO'),
    pax('5K', 'NOREÑA', 'ROSARIA'),
    pax('6A', 'OCAMPO', 'SAMUEL'),
    pax('6B', 'PALACIO', 'TERESA', undefined, ['VGML']),
    pax('6C', 'QUIJADA', 'UVALDO'),
    pax('6D', 'RESTREPO', 'VIOLETA'),
    pax('6E', 'SEPULVEDA', 'WILLIAM'),
    pax('6K', 'TABARES', 'XIMENA'),
    pax('7A', 'URREA', 'YESID'),
    pax('7B', 'VASCO', 'ZOILA'),
    pax('7K', 'ARBELAEZ', 'ALBA'),
    pax('8A', 'BEDOYA', 'BLAS'),
    pax('8B', 'CARVAJAL', 'CLARA'),
    pax('8C', 'DUQUE', 'DARIO'),
    pax('9A', 'ESTRADA', 'ELENA'),
    pax('9B', 'FLOREZ', 'FABRICIO'),
    pax('9K', 'GAVIRIA', 'GRISELDA'),
    pax('10A', 'HENAO', 'HUMBERTO'),
    pax('10B', 'IDARRAGA', 'ISABEL'),
    pax('11A', 'JIMENEZ', 'JORGE'),
    pax('11B', 'KURI', 'KAREN'),
    pax('11C', 'LOPERA', 'LUIS'),
    pax('11D', 'MOLINA', 'MARIA'),
    pax('11E', 'NARANJO', 'NESTOR', undefined, ['BBML']),
    // Economy (filas 12-32)
    pax('12A', 'OBANDO', 'OLGA'),
    pax('12B', 'PIEDRAHITA', 'PABLO'),
    pax('12C', 'QUINTERO', 'RAQUEL'),
    pax('12D', 'RINCON', 'SERGIO'),
    pax('12E', 'SALAZAR', 'TATIANA'),
    pax('12K', 'TRUJILLO', 'URIEL'),
    pax('14A', 'VASQUEZ', 'VIVIANA'),
    pax('14B', 'WILLS', 'XAVIER'),
    pax('14C', 'YEPES', 'YENNY'),
    pax('14D', 'ZAPATA', 'ZEUS'),
    pax('14E', 'ACOSTA', 'ALBA', undefined, ['PETC']),
    pax('14K', 'BERNAL', 'BORIS'),
    pax('15A', 'CASTILLO', 'CARMEN'),
    pax('15B', 'DELGADO', 'DELFIN'),
    pax('15C', 'ECHAVARRIA', 'ESMERALDA'),
    pax('15D', 'FIGUEROA', 'FELIX'),
    pax('15E', 'GIRALDO', 'GLORIA'),
    pax('15K', 'HINCAPIE', 'HECTOR'),
    pax('16A', 'IBARRA', 'INES'),
    pax('16B', 'JAIMES', 'JAVIER'),
    pax('16C', 'LEMOS', 'KARINA'),
    pax('16D', 'MAZO', 'LETICIA'),
    pax('17A', 'NIETO', 'MARCOS'),
    pax('17B', 'OSSA', 'NANCY'),
    pax('17D', 'PARRA', 'OSCAR'),
    pax('17E', 'QUICENO', 'PAOLA'),
    pax('18A', 'RODRIGUEZ', 'RAUL'),
    pax('18B', 'SANCHEZ', 'SONIA', undefined, ['CHML']),
    pax('18C', 'TEJADA', 'TOMAS'),
    pax('18D', 'UPEGUI', 'UNA'),
    pax('19A', 'VELASQUEZ', 'VICTOR'),
    pax('19B', 'ZULUAGA', 'WENDY'),
    pax('19C', 'ARENAS', 'XAVIER'),
    pax('19D', 'BAENA', 'YOLANDA'),
    pax('20A', 'CALLE', 'ZULMA'),
    pax('20B', 'DIAZ', 'ANDRES'),
    pax('20C', 'ESCOBAR', 'BLANCA'),
    pax('20D', 'FRANCO', 'CAMILO'),
    pax('21A', 'GARCIA', 'DIANA'),
    pax('21B', 'HERRERA', 'EDUARDO'),
    pax('21C', 'IRISARRI', 'FANNY'),
    pax('22A', 'JORDAN', 'GABRIEL'),
    pax('22B', 'KUREISHI', 'HASSAN'),
    pax('22C', 'LEIVA', 'INGRID'),
    pax('23A', 'MORALES', 'JAIR'),
    pax('23B', 'NIEVES', 'KELLY'),
    pax('24A', 'OLARTE', 'LIDA'),
    pax('24B', 'PALOMINO', 'MIGUEL'),
    pax('24C', 'RIOS', 'NUBIA'),
    pax('25A', 'SERNA', 'OMAR'),
    pax('25B', 'TAMAYO', 'PILAR', undefined, ['FSML']),
    pax('26A', 'URIBE', 'QUIRINO'),
    pax('26B', 'VEGA', 'ROCIO'),
    pax('27A', 'WALTEROS', 'SAUL'),
    pax('27B', 'YATES', 'TERESA'),
    pax('28A', 'ZAPATA', 'ULISES'),
    pax('28B', 'ANGEL', 'VALENTINA'),
    pax('29A', 'BOTERO', 'WALTER'),
    pax('29B', 'CORTES', 'XIMENA'),
    pax('30A', 'DAVILA', 'YAMILE'),
    pax('30B', 'ERAZO', 'ZEUS'),
    pax('31A', 'FAJARDO', 'ALBA'),
    pax('32A', 'GARCIA', 'BEATRIZ'),
    pax('32B', 'HURTADO', 'CARLOS'),
    pax('32C', 'IBAGON', 'DIANA'),
    pax('32D', 'JARAMILLO', 'EDGAR'),
    pax('32E', 'KLEE', 'FERNANDA'),
    pax('32K', 'LEON', 'GUSTAVO'),
  ],
};

// ─── Vuelo 3: AV8513 BOG → CTG — A319 (costa corto) ──────────────────────────
export const FLIGHT_AV8513: FlightManifest = {
  flightNumber: 'AV8513',
  date: '03 JUN 2026',
  aircraftType: 'A319',
  origin: 'BOG',
  destination: 'CTG',
  infantCount: 2,
  passengers: [
    // Business (filas 1-3)
    pax('1A', 'LLINÁS', 'RAFAEL', 'DIAM'),
    pax('1C', 'BARRANQUILLA', 'MARINA', 'GOLD'),
    pax('1D', 'CAMPO', 'DAVID', 'GOLD'),
    pax('1K', 'DIAZ', 'CONSUELO'),
    pax('2A', 'ESPINOSA', 'FIDEL', 'DIAM'),
    pax('2C', 'FUENTES', 'GRACIELA'),
    pax('2D', 'GAMBOA', 'HERNAN'),
    pax('2K', 'IBAÑEZ', 'JACINTA', undefined, ['VGML']),
    pax('3A', 'JARABA', 'KEVIN'),
    pax('3C', 'LEAL', 'LINA'),
    // Plus (filas 4-9)
    pax('4A', 'MARTINEZ', 'MARIO', undefined, ['WCHR']),
    pax('4B', 'NAVARRO', 'NATALIA'),
    pax('4C', 'OLMOS', 'OMAR'),
    pax('4D', 'POLO', 'PATRICIA'),
    pax('4E', 'QUIÑONES', 'RAUL'),
    pax('4K', 'REALES', 'SANDRA'),
    pax('5A', 'SIERRA', 'TOMAS'),
    pax('5B', 'TORRES', 'URSULA'),
    pax('5C', 'ULLOA', 'VALENTINA', undefined, ['GFML']),
    pax('5D', 'VIVEROS', 'WILLIAM'),
    pax('6A', 'YAÑEZ', 'XAVIER'),
    pax('6B', 'ZARATE', 'YOLANDA'),
    pax('6C', 'AVILEZ', 'ZEUS'),
    pax('6K', 'BAYONA', 'ALBA'),
    pax('7A', 'CABAS', 'BORIS'),
    pax('7B', 'DACONTE', 'CARMEN'),
    pax('7C', 'ECHEVERRIA', 'DIEGO'),
    pax('7D', 'FALS', 'ELENA'),
    pax('8A', 'GARCIA', 'FRANK'),
    pax('8B', 'HERREÑO', 'GINA', undefined, ['BBML']),
    pax('8C', 'INSIGNARES', 'HORACIO'),
    pax('8K', 'JARAMILLO', 'IRIS'),
    pax('9A', 'KURE', 'JOSE'),
    pax('9B', 'LARA', 'KATIA'),
    pax('9C', 'MANCILLA', 'LEANDRO'),
    pax('9D', 'NIÑO', 'MAGNOLIA'),
    // Economy (filas 10-28)
    pax('10A', 'OROZCO', 'NICOLAS'),
    pax('10B', 'PALMA', 'OFELIA'),
    pax('10C', 'QUEVEDO', 'PEDRO'),
    pax('10D', 'RAMOS', 'QUINTIN'),
    pax('10E', 'SUAREZ', 'RAQUEL'),
    pax('10K', 'TOVAR', 'SERGIO'),
    pax('11A', 'URIBE', 'TATIANA'),
    pax('11B', 'VASQUEZ', 'URIEL'),
    pax('11C', 'WALTEROS', 'VALERIA'),
    pax('11D', 'YEPEZ', 'WILLIAM'),
    pax('11E', 'ZAPATA', 'XIOMARA', undefined, ['SVAN']),
    pax('11K', 'ARAGON', 'YURI'),
    pax('12A', 'BALLESTAS', 'ZEUS'),
    pax('12B', 'CANTILLO', 'ALBA'),
    pax('12C', 'DORIA', 'BLAS'),
    pax('12D', 'ELLES', 'CLARA'),
    pax('14A', 'FONTALVO', 'DARIO'),
    pax('14B', 'GUERRERO', 'ELENA'),
    pax('14C', 'HERRERA', 'FELIX'),
    pax('14D', 'INSIGNARES', 'GLORIA'),
    pax('14E', 'JABBA', 'HORACIO', undefined, ['MEML']),
    pax('14K', 'KURE', 'IRIS'),
    pax('15A', 'LEMAITRE', 'JOSE'),
    pax('15B', 'MELO', 'KAREN'),
    pax('15C', 'NAVARRO', 'LUIS'),
    pax('15D', 'ORTEGA', 'MARIA'),
    pax('16A', 'PATERNINA', 'NESTOR'),
    pax('16B', 'QUINTERO', 'OLGA'),
    pax('16C', 'RAMIREZ', 'PABLO'),
    pax('17A', 'SALCEDO', 'QUIJANO'),
    pax('17B', 'TOBAR', 'ROSARIA'),
    pax('17D', 'URQUIJO', 'SAMUEL'),
    pax('18A', 'VILLADIEGO', 'TERESA'),
    pax('18B', 'WILLS', 'ULISES'),
    pax('19A', 'YEPES', 'VALENTINA'),
    pax('19B', 'ZUÑIGA', 'WALTER'),
    pax('20A', 'ACOSTA', 'XIMENA'),
    pax('20B', 'BUELVAS', 'YOLANDA'),
    pax('21A', 'CAMPO', 'ZEUS'),
    pax('21B', 'DAZA', 'ALBA'),
    pax('22A', 'ELIAS', 'BEATRIZ'),
    pax('22B', 'FLOREZ', 'CAMILO'),
    pax('23A', 'GARCIA', 'DIANA'),
    pax('23B', 'HERRAN', 'EDGAR'),
    pax('24A', 'IBARRA', 'FANNY'),
    pax('24B', 'JARABA', 'GABRIEL'),
    pax('25A', 'KURE', 'HELEN'),
    pax('25B', 'LEAL', 'IGNACIO', undefined, ['CHML']),
    pax('26A', 'MANOTAS', 'JULIA'),
    pax('26B', 'NIETO', 'KEVIN'),
    pax('27A', 'OTALVARO', 'LUPE'),
    pax('27B', 'PACHECO', 'MARIO'),
    pax('28A', 'QUINTANA', 'NURIA'),
    pax('28B', 'ROMERO', 'OMAR'),
  ],
};

export const DEMO_FLIGHTS = [FLIGHT_AV028, FLIGHT_AV9114, FLIGHT_AV8513];
